---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: node-red
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2de665b00000001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red
  namespace: shared-services
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: node-red
