apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 750Mi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 750Mi
