apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - namespace.yaml
  - volume.yaml
  - release.yaml
configMapGenerator:
  - name: harbor-config
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
