expose:
  tls:
    certSource: secret
    secret:
      secretName: harbor-ingress
  ingress:
    className: contour
    hosts:
      core: harbor.web.craigcloud.io
      notary: notary.web.craigcloud.io
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
externalURL: https://harbor.web.craigcloud.io
harborAdminPassword: Password#1
persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-registry
    jobservice:
      jobLog:
        existingClaim: harbor-job
    database:
      existingClaim: harbor-db
    redis:
      existingClaim: harbor-redis
    trivy:
      existingClaim: harbor-trivy
