---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry
spec:
  capacity:
    storage: 256Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: harbor-registry
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2e0fe7000000007
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: harbor-registry
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-job
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: harbor-job
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2e0fe7100000008
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-job
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: harbor-job
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-db
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: harbor-db
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2e0fe7200000009
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-db
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: harbor-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-redis
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: harbor-redis
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2e0fe730000000a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-redis
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: harbor-redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-trivy
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: harbor-trivy
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2e0fe6f00000006
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-trivy
  namespace: harbor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: harbor-trivy
