apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vxflexos
  namespace: vxflexos
spec:
  releaseName: csi-vxflexos
  chart:
    spec:
      chart: csi-vxflexos
      sourceRef:
        kind: HelmRepository
        name: csi-powerflex
        namespace: flux-system
      version: "2.5.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
