apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: media
spec:
  releaseName: minecraft
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
      version: "4.9.0"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: java17
    resources:
      requests:
        memory: 4096Mi
    minecraftServer:
      eula: "TRUE"
      type: "PAPER"
        paperDownloadUrl: "https://api.papermc.io/v2/projects/paper/versions/1.20.1/builds/18/downloads/paper-1.20.1-18.jar"
      difficulty: normal
      ops: nctiggy
      viewDistance: 15
      levelSeed: 7644964991330705060
      memory: 4096M
      forcegameMode: true
      icon: "https://styles.redditmedia.com/t5_o6oqi/styles/communityIcon_a9ptdumocik11.png"
      onlineMode: false
      enforceSecureProfile: false
      serviceType: LoadBalancer
      loadBalancerIP: 192.168.0.54
      persistence:
        dataDir:
          enabled: true
          Size: 64Gi
          existingClaim: minecraft
