apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.0.3
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            probes:
              liveness:
                enabled: false
              startup:
                enabled: false
              readiness:
                enabled: false
            image:
              repository: lscr.io/linuxserver/calibre-web
              tag: 0.6.20
    ingress:
      main:
        enabled: false
      calibre-web:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: calibre-web
          hosts:
          - calibre-web.web.bluehairfreak.com
        hosts:
        - host: calibre-web.web.bluehairfreak.com
          paths:
          - path: /
            pathType: Prefix
            service:
              name: calibre-web
    service:
      main:
        enabled: false
      calibre-web:
        enabled: true
        controller: main
        ports:
          http:
            port: 8083
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web
      media:
        enabled: true
        existingClaim: nfs-share
