---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web
spec:
  capacity:
    storage: 128Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: calibre-web
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2e0893b0000000c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: calibre-web
