apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: "0.11.0"
  interval: 30m
  install:
    remediation:
      retries: 3
  dependsOn:
  - name: sealed-secrets-controller
    namespace: kube-system
  valuesFrom:
  - name: metallb-values
    kind: Secret
    optional: true
  - name: metallb-config
    kind: ConfigMap
    optional: true
