apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: "3.10.0"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    defaultArgs:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --cert-dir=/tmp/ca
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
