apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: vault-config
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
