---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-gitops
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: 0.15.0
  install: {}
  interval: 1h0m0s
  valuesFrom:
  - kind: ConfigMap
    name: vault-config
