apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: "0.11.0"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    configInline:
      address-pools:
      - name: frontend
        protocol: layer2
        addresses:
        - 192.168.0.50-192.168.0.59

