apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: bitnami-labs
        namespace: flux-system
      version: 1.16.1
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    dashboards:
      create: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/ingress.class: contour
        kubernetes.io/tls-acme: "true"
      tls:
      - secretName: sealed-secrets
        hosts:
        - secrets.web.bluehairfreak.com
      hosts:
      - secrets.web.bluehairfreak.com
