apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: bitnami-labs
        namespace: flux-system
      version: 1.16.1
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    dashboards:
      create: true
