apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  releaseName: radarr
  chart:
    spec:
      chart: radarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "16.0.1"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: radarr
          hosts:
          - movies.web.bluehairfreak.com
        hosts:
        - host: movies.web.bluehairfreak.com
          paths:
          - path: /
            pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: radarr
      media:
        enabled: true
        existingClaim: nfs-share
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
      serviceMonitor:
        labels:
          prometheus: scrape
