apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: shared-services
spec:
  releaseName: vaultwarden
  chart:
    spec:
      chart: vaultwarden
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "3.3.1"
  interval: 30m
  install:
    remediation:
      retries: 3
  dependsOn:
  - name: sealed-secrets-controller
    namespace: kube-system
  values:
    image:
      tag: 1.25.0
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
          projectcontour.io/websocket-routes: "/notifications/hub"
        tls:
        - secretName: vaultwarden
          hosts:
          - passwords.web.craigcloud.io
        hosts:
        - host: passwords.web.craigcloud.io
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub/negotiate
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub
              pathType: Prefix
              service:
                port: 3012
    persistence:
      config:
        enabled: true
        existingClaim: bitwarden
  valuesFrom:
  - kind: Secret
    name: vaultwarden-values
