apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.12.1"
  interval: 1h0m0s
  dependsOn:
  - name: metallb
    namespace: metallb-system
  install:
    remediation:
      retries: 3
