apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 16Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /
    server: 192.168.0.59
    readOnly: false
