apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
spec:
  releaseName: frigate
  chart:
    spec:
      chart: frigate
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "8.0.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: 0.10.1-amd64
  valuesFrom:
    - kind: Secret
      name: frigate-values
      optional: true
