apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  releaseName: sonarr
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "^15.2.0"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: sonarr
          hosts:
          - tv.web.bluehairfreak.com
        hosts:
        - host: tv.web.bluehairfreak.com
          paths:
          - path: /
            pathType: Prefix
    persistence:
      config:
        enabled: true
        skipuninstall: true
        size: 64Gi
      media:
        enabled: true
        existingClaim: nfs-share
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    addons:
      codeserver:
        enabled: true
        volumeMounts:
        - name: config
          mountPath: /data/config
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            ingress.kubernetes.io/force-ssl-redirect: "true"
            kubernetes.io/ingress.class: contour
            kubernetes.io/tls-acme: "true"
          tls:
          - secretName: sonarr-code
            hosts:
            - tv-code.web.bluehairfreak.com
          hosts:
          - host: tv-code.web.bluehairfreak.com
            paths:
            - path: /
              pathType: Prefix
