apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "10.0.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: 2022.3.8
  valuesFrom:
    - kind: Secret
      name: home-assistant-values
      optional: true
