apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash
  namespace: stash
spec:
  releaseName: stash
  chart:
    spec:
      chart: stash
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "3.2.0"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: v0.13.0
  valuesFrom:
  - name: stash-values
    kind: Secret
    optional: true
