imageTag: "7.9.1"
concourse:
  worker:
    runtime: containerd
  web:
    clusterName: home
    enableBuildRerunWhenWorkerDisappears: true
    enablep2pVolumeStreaming: true
    externalUrl: https://concourse.web.craigcloud.io
    kubernetes:
      namespacePrefix: concourse-
secrets:
  githubClientId: 7b4b4768808eab5c6a7b
  githubClientSecret: f17f1fcbf7be09c677279f813b2ef9c67b930d3d
web:
  ingress:
    enabled: true
    hosts:
    - concourse.web.craigcloud.io
    ingressClassName: contour
    tls:
    - secretName: concourse-tls
      hosts:
      - concourse.web.craigcloud.io
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/force-ssl-redirect: "true"
