apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jenkins-values
  namespace: jenkins
spec:
  encryptedData:
    values.yaml: AgAK9x7ToaXltU8fuvSIyK2dFu/jBo1AhyxB+osk1dpzR+9f1XjlVy77p/TwnUPj5mqaQPNxiooW11i9Mh1yWDXn0Gg/sEZ3bVSYgsavSaRwBq0ZdqlEPhp8WJ8JOQl7PAMzoZ56An8tZgDQsoU76aY49YsPeJOShzlbvAxi4xik+ID4oUDSPNAoqxhOe00CPhIDLVf0mEs2Y51Hf9DmnibbKqaYAqX/XcdXpw+CeVxuuIy2VCMPBRG8ZrkVZkvdaFsrvolMmCou7Uz/yZkg5YBtzxj6vihWi7We8WPa0hQcxU8u+zoLyr8d2d8IDJmk7lAGHE6Z6LY59QYGNYCKVc5Gcet9Iy//MUjGbLW6HifyXJNWVcrtqEO90q52fnNfL3K4YONjUxGdnqp7DuJJDUbmXSJEfHpig7lJh//QQlMYxGL1iZTVfQnIkUZLpBzx7HzcJESg4xsd8QjLFx3LyZrl/i8kOmHthCfCO92QtElHlLLx2yA6TQn403mVAnDs5CO4sNVFvl3pYiVQLTBFk2yz8RzyjxUWf3sFIPnqUTTa0Oyq8rAtjqL8bFyW1UKtK6QIeJkXkO2/H1yjtzJUOX7dIVUo1YBUV6l0Q+LKse1JXwBxIoRTQqW0RPGSk69IrkHQL0FPH59VGMrLb2wvGZcamftcWrWeJoDLRs3UTAfn8upGJFqIF34RvKTCg8g912xaH+guBonZuyzkxN8PEDUCs2X6MKNcRoQmipMODqbETxWbbWnGdJhIFlY68WuoMaaXLyHhu0+ML0mPzfcB6p/K04EFRaBpESb4UpvL8q6ayPKxunk8BehzAm+NP+f5enJwDsxJCo3mbR6X3FVPGqnpOj0M4B7cjGsVz9R1HZ6PMPHxJRI+u/uuvqIzXnYfkkFbj22Ka4aQl+WQ22rhmIINtjmB1Ayy80Bc6LehEZCXDC2yecBICkGl+b6D3odHoFaeppVJ0P/wVlTVRoGTHQlzHeKBsuxgmYd42v+RMQarJOge8OcniU5XpAveymgrQWCQeZb1eFa70gfBKXYw0CRkyUh7+yzbyHIn+Tvlmq9dQyK6czdHJ84JCjblemByjv14PaX1cxsal9IcGFUTVfwLmTtrv+2MHn9DojHcoE3D7ZjpzoOYacEiNvGsouR7ArSbjnTht9UL+M7fr47RJ2hfzFFWGTWJSvdIb45EyCrxll6pGQazV7S2zQnmyAamdacV2cYT+UKLb3LVjAYqt91cpuWOv2JyeIjxcs0zpDNOMdwWTxZYsW2cfQHNttDAOArBtkZqqN9FQu2ZuakdDCjkhxgVJ/PFw5P6KON2sKfnKAPfy+PzbhGmVXmWhMY/6KUHOoayeFX+Vaa4gZ/K694XunPYhg==
  template:
    metadata:
      creationTimestamp: null
      name: jenkins-values
      namespace: jenkins

