apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  releaseName: plex
  chart:
    spec:
      chart: plex
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "6.2.0"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    hostNetwork: true
    image:
      repository: plexinc/pms-docker
      tag: 1.32.0.6973-a787c5a8e
    env:
      TZ: "Americas/Los_Angeles"
      ADVERTISE_IP: "http://192.168.0.52:32400"
      ALLOWED_NETWORKS:
      - 127.0.0.1
      - 192.168.0.0/24
      PLEX_CLAIM: "claim-BS4vvTL41zFh7e6SS9cs"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "192.168.0.52"
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: plex
          hosts:
          - plex.web.craigcloud.io
        hosts:
        - host: plex.web.craigcloud.io
          paths:
          - path: /
            pathType: Prefix
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: "nfs-share"
      config:
        enabled: true
        type: pvc
        existingClaim: "plex"
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - nfs-server
          topologyKey: "kubernetes.io/hostname"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
