---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: plex
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2deb47f0000000b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: plex
