apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  releaseName: contour
  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "10.1.3"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
