apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  releaseName: gitea
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      version: "v6.0.3"
  interval: 30m
  install:
    remediation:
      retries: 3
  dependsOn:
  - name: sealed-secrets-controller
    namespace: kube-system
  valuesFrom:
  - name: gitea-values
    kind: Secret
