---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-db
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: gitea-db
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2dfecfa0000001d
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-db
  namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: gitea-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea
spec:
  capacity:
    storage: 72Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: gitea
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2dfecf90000001c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: gitea
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 72Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: gitea
