apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kapowarr
  namespace: media
spec:
  releaseName: kapowarr
  chart:
    spec:
      chart: kapowarr
      sourceRef:
        kind: HelmRepository
        name: nctiggy
        namespace: flux-system
      version: "0.0.3"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: mrcas/kapowarr
      tag: latest
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: kapowarr
          hosts:
          - comics.web.bluehairfreak.com
        hosts:
        - host: comics.web.bluehairfreak.com
          paths:
          - path: /
            pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /app/db
        existingClaim: kapowarr
      media:
        enabled: true
        existingClaim: nfs-share
