---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kapowarr
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: kapowarr
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2e0b04900000002
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kapowarr
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: kapowarr
