apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- snapshot.storage.k8s.io_volumesnapshotclasses.yaml
- snapshot.storage.k8s.io_volumesnapshotcontents.yaml
- snapshot.storage.k8s.io_volumesnapshots.yaml
- rbac-snapshot-controller.yaml
- setup-snapshot-controller.yaml
