apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: telly
  namespace: media
spec:
  releaseName: telly
  chart:
    spec:
      chart: telly
      sourceRef:
        kind: HelmRepository
        name: nctiggy
        namespace: flux-system
      version: "0.0.2"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: tellytv/telly
      tag: dev-ffmpeg
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "192.168.0.51"
    persistence:
      telly-config:
        name: telly-config
        enabled: true
        type: secret
        mountPath: /etc/telly/telly.config.toml
