apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: xbackbone
  namespace: xbackbone
spec:
  releaseName: xbackbone
  chart:
    spec:
      chart: xbackbone
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "^5.1.0"
  interval: 30m
  install:
    remediation:
      retries: 3
  valuesFrom:
  - name: xbackbone-values
    kind: secret
    optional: true
