apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
spec:
  releaseName: minecraft
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: flux-system
      version: "4.2.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: java17
  valuesFrom:
    - kind: ConfigMap
      name: minecraft-config
    - kind: Secret
      name: minecraft-secret
