service:
  type: ClusterIP
ingress:
  enables: true
  pathType: Prefix
  path: /
  hostname: jenkins.web.craigcloud.io
  tls: true
  ingressClassName: contour
  certManager: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
persistence:
  size: 64Gi
jenkinsUser: admin
jenkinsPassword: Alisha2
jenkinsHost: jenkins.web.craigcloud.io
