apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev-ops
  namespace: flux-system
spec:
  dependsOn:
  - dialtone
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./dev-ops
  prune: true
  validation: client
