apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media
  namespace: flux-system
spec:
  dependsOn:
    - name: dev-ops
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./media
  prune: true
  validation: client
