apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2
spec:
  releaseName: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      version: "5.0.6"
  interval: 30m
  install:
    remediation:
      retries: 3
  dependsOn:
  - name: sealed-secrets-controller
    namespace: kube-system
  valuesFrom:
  - name: oauth2-values
    kind: Secret
    optional: true
  - name: oauth2-config
    kind: ConfigMap
    optional: true
