{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "frigate-values",
    "namespace": "frigate",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "frigate-values",
        "namespace": "frigate",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "values.yaml": "AgAsVu3eE43vnqcJ7H2gC0M066pNvtaNLIa3InJpVZ5VW7q+Ykvloqtbhn8VWu4HMwTQIHsVGx4sWzeIWOpQmF8+RBJm3Gl2itLDllOXBmV8jX1OeyFK1M6kRbizixBgDmdkUb9QnqTCRwLZPwYotPhSSyYrCBXskxlKYYVz4tgY53nWMr30W9JgIsndudqqFEZ1X1FE6Z6ALrhTptSRWtyBGaDBeMgCSZgQZYhnVfLbPqLEruZPiWwUiuGOZuXofXslRn+xyKJ7c40R4EnaqCv5eBKngubkolJYkw61luO7hV0aaIPPRvVAflshj3SyGiYg5H28331CBcL2GQ7fEmMsiSzQkbGcdajKah5emY3GCnyW4kH09pOzAhF3rCnv4lQXxxK4e/RwyCADLrcUAwrReFGfu51TsZk0gEsrE0Gt7PaE7QuAYldhaxBBh0/78j6wjOyJCC4QET/HJC3yiXonW1N0xCJXCPbvVQGWERnc45vbJhBa4X1KmbwGsM2VC9z8ObyTHhNpBI8jIWoJV08jJeXqkKMXxCCgB2mCWNM2JbiRFP5r1wIcS+TdbZ2L3xCZIqlYwh2476ccbVYciU05DKNCR4koF+M1R2C8QRZab22mIcgSFg4Mo+shAMKyCpow57OkXDJA/nN1SBNDiYhL+AjeXKT/V1PBF/zFB6XzR8U+XMNg/GaeKf3Phm1rht3xN1/WgbOR4pRGZaiuLvoRWKBC5D5RdDIAkT712Cxnyzp+RGCpHDjKloqQRA8uPTg5SMStTGIG6jWG/YEC/RK/osWANqS0PKSUeCStQBNum4QFgrN2etYgzohQU/25eT8Oe62ongjxsTyREijk5Pl4jrftydaQoezf3HvGyF/7NDBKSOqmWW7AFnefP2+wZJf2r3zpyi+MdLu4d1BVtB/X3Xn96TksRH0FnDP3fmLPyBI+W0VHBpvNvf5gQpk2Ex4wPpi3SlDWar7w02Nvr53854lpC1Xoe0hWyCas184Hs/og07G9r1g51gJOtFKTQx7vgne8Oa+P/CfFAg0PYdXQo61ndN4bN/s+cPw2of9OXpYF3AB2F/P5jY/qdX5rT6c3AfCYRDly+lt7TlA3FSvyEa2S17fy/XH7eAl+yTzgL2U6c39XH4rlfAkafcprHWnsFLnx5TcFot6VDDU//Da++Z0MGKV7aEz4Mv1hj2V3S5Cuqw1X5FFJ/arD4b105QynfWP6LAfmPD3altyCcPbjNrgAr5MZo67DfxG/GzKWUWlYHtkDbxNO5olHEg7wdYyAG0kgYsMv43CTxowlJ3ZytZm/+qJMZhBu0n6h0QJsMRw44U+H3WslCULHuWYbu9BGrGAKaxPFUKbHm3z4Zdg7lEaYbcHQ/N4Mestfb0BLsxkdy/8myLAUjYeTFKSOYDt1m1QpY2fs+RiN+X0fliArqEoLRwtX6dxdaOmn+KcHkJy5vpDrJTV5JzRzChUYKj5xF7//6dgopyYkwJUMsIH96etTyztiJlg8Munbq50dIUZJWR3sUuckyBiXNqs/CFFv92h2qhXjvUjrjsxJlS2tsJx4KZhFYX4rXqCG9lCjTYAM7mfujki6R0qDGZEgloAlanmLLGtY5++UGEVVbrGHNIdJuEOS5ylktlfrj7dttCSsRQO5f0v+H83WS8UNtpODjEgJ78KxSBZEsJkaWATLV6wOT2b1JLFPb9QRSXOG19/bMeC2mnumxCylVP8/x8XnHNlZWizl7aOPpfZRatHWGqy+nalRt+/ddHummHsQW3snbkpUAxA+Xi2P/PlM4KnBLCrxDDVLKfIlDmGnxRwiBIXaI5uHGSYvueA3zQtmP5BAwYBKriGh4JsF47/DC+vIDSrxQ0QxXWNor1Qx7oTzk+oIsFayNTiCFcp0K4uVNgI7FTWcDhfVePQj1XKkk16HCOu5ZiUKlh77BykA8MwiAW+nWsw0e7g7nXJyWTM0eLDfGrR4RhPpSEoznwe5XBqkFq8KiB33wIyOyoJQf3o/eDsQ+2qZCVruQ7enaRW1oy9xVTF5wDMKd2SgHcV8CUgHOSfoEhYRBg/5K1gXj20YYjW2g68x2oViPk1uO7JtpMt+F0T4XAbpd14BsTvehCN4yBMEx2AgCDulvQRvjEEqPQ=="
    }
  }
}
