{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "frigate-values",
    "namespace": "frigate",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "frigate-values",
        "namespace": "frigate",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "values.yaml": "AgBZlbw9l6ruGyFZrZcjbdoUKrTyW1etJqW8ilCz4Lhg2xh4dMH4AgBA5cpZ9jMH02pbSaWOkUxNHcCkoKhRWTGznSUxeK9rhloNeJYEUBeTD5kSYbLMmsnEz4CV1v9PGSc0UoBnhPuM39ScUUZcIBXg/MCUTonfJkmdetCoick0+40Xt2Yy7g10Yp6zybFSrKik2Ojfl7VEQMzIwbZgSBoDhWQZOYZ0MXbcZt1XJwKT6R+AIUJRt8W7ODtEHEK2TTWXOudUJ3jsIB9n6w7DU47BK4C90k1XDJiPoSbjkdPX3u3czaSZGN29VnLPOotRL22pc8IVV9f3QY6BE8oYPajycVOfRnx04oCx+PNKYBXixYsH+GVACWNlNKMCTDD2lYh7y7wuFlZeqaiA29sV9Y8DY6aLpdmoGsIESTg3eXq65lLQijUReIbpqgZ+JQ86Qwy1eR8a8cArnkdK+UcBhPcUS40UWjTsSlQZ8QA9qBmVDrdO2ElqRL77LsHrQn9rE1t3P74XKmf0dFoKXmyBdCBwPexE6Q+YIrfCYdzCu/NBBeN5BitTn69DEWugM0IYk4Y1Ute06y4TVPRQ5K55o+qC8qRY9uMv8hDVr6T8WfSfFglXjgqiMx1FGTKrFcVWVe00XUKtYcCCSZBXhhyFiX+/TXEJQFt6JD4hjLhjhY5Cq/P0yRZXKbKwvtH0Q3hB+BBBffe6VklVGUiwp0aOBNi9eBcHQD4KVYDsjoftoO1LRCyW1TF9FdrHIBOwjcJM8ywmi4LWO+dEDufSBMo3CLq26rXV6hNENV/edoSDJJwKrIa+mjf44xPP0E3rkfKiQpfYprdsTVVXXxGIoMnMJrQi/SLnAIqT76y1sYKGoC18sQ7hHqgWaPKBnvwbCk31ujFQmuheVMcgZm6j8qmnDtsCHK5S9uZF3hpH10vVsagmzjG01UmZ2fXwAmkB4pJ7DqxOl8KqD5xTyD/ULkG1e/LA7FWb3L9JypVa15PLUvrEmNLXrV7dkaHmxG6vFNEQnYnifG/OKc3QyfGwjQpwMlQhL3OcrNd3X3jtayre4CRFUJxzDZHhBbkQ5yLAhjBGzSEzgS4mmsyQ6KGd+HixvqdTxAv1qdbNCGjyJmx88EKbLD5/IedRSh/XG80bhDVCt/iBcXdy0Ei87kPcLqpyJcSzUAFZjoMp2WeHryBjwa491Zriz/MdFihKLEs7+ctzGU9ptwONbBRbETJ6lMosei7fDklmdUfvH/rtyRxC+cvq78+/dWx9OTGj9mXHzWxQCFhIk3SOgshIbWDJrYf30rrx9VUZr8tzkDWwOiAgzWIZ0qcaGKxpKHlOxxFV2y7Fl65I95QyGnEeKN+C7WtjrIB+TgDCVy/d0An1bUmby2jB5LcNpLIx7Z6Xlrss3RG4aET5bRg9/ObgxJMna2jhZwXjFeGqs5/SS0iYlFgvgAAJkDJoaNS/3ELp6bjssISm+IL5yJeUg2d90p7lIG3GM+YT4hnsHusGm8Ob5qLmX86gNmconRmImpba0KxnJqPNWgdUbgd43Ygp3b9uFlY7v1TvDGCx4KgGdBCRbw9dW0g8fUd18nYVcsnMAjPmQCiGOXM0pXPseVIgC3JSQXCJg3VwhvupzizFp8TI7zJ/F92WauIkQxKAAZm+Cl2gBtwD2XNnYO2apeqN3z+qLwgqnIwLte/hawVmV0y4sO2YHQIQC/yEh9GmAD7boCSn29+ubTxuzbc+eka12z1bAmWTAjzWw+ZYssKsF5LxIv7DgD6rOhmYUTHjyysCOIoYbJLwiAJv7eVNHTfVFxpCLDRubwyxsVrQfpSkKOuISpviPygiGmayEiJFBR1RXpzOMDc1KGDz0bfhe14nhuvvi99GwhiHaC7SZAmm5Y7jpzDCtBZih4gYwHC2ZDKOERlK1d0r9i2/FWOBCatAljEXZSc+ukzR5rUdBlg2njWZC0JAMvu9d9lK9C8kLeDYah3qifcgwRQIePq0vofebTkhVH8BTHDfJFGJzX9ePPO8S5XLtuEkJ7jOC3j8dhm/NyUEihfHoaxZfmzIF5UQKE5lREnvfkLgmS6eTX1PnX64OzZVWmMpTQe094AgAzvPlQHEh7ZEpDa5r48P64OWKvYv/5gFq2sAl+J/us3jWEjRhqjZP4JE+UftWV+o0xBh"
    }
  }
}
