{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "frigate-values",
    "namespace": "frigate",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "frigate-values",
        "namespace": "frigate",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "values.yaml": "AgAF144Kfz2Bpao+zRGef3i67Pmfyq8ymutD5q5tM/82O9g8QaZvIr+YZ84vx7UwQXP0YrHRrBLS6mA43SN38qznGZ7DC5GvtSwZQD1WhOpwSJ3eF7zFe9E89YDNc83ESZKL01sTmRw37Hgl6jE6KJQ1/HIhCCG9r785u+1abXmiwywN5MusIRnBL6+vu+/7BFVinD5iJA9m5F/6i3z46rvRo2ZPowmMuGfCOdsKJT5VKXkUnnIPY+G7PbCttvYTCzz2H1n4W/AkcXhAr6+Gxvmo1E5bAwLC0d+zWQvSD1Ku4L0GmUnE0HyuykjwEAAAlPQQ1/OWRZWW3i6q6WV4st3mQkGbs4B+CkHTz6oqTFFCJGtARDZU+6WMOBcjD9NlY1sAxncKDYb1Lz8k14MfU3WJZEKVknxRDuA0A8nWyif2rV4TjztdWzPh3Gp+Jw5fgDMAt9UZ3eyV+7Iw5R4Cn+2Ow/JDiSyqStVIkkz8eaN9FyzOM15UKmiUh9QNaR7cFAfD1hbxTpZQUuFYwV4XSdqS8MnbNh8OwTa3DckgmBpO5CkLm3UqKMqBT4yg1CkZathemuotgH4NcC+Mj/FtO+TY2O563biYl+WsSSA5fpLpcDcSb5p+aD7uFfgocpc8YV0R93QykEeuL4A9mSgUSt/ovo46ZOntfhdibnjtKxmY1bezYVxAXJ2uBsUk2je48t98zrbHcKBtzLqMt/CTYZeS3MF8sjymdhEWFQw/cTysvQ7oBBNHQqKvcchaMqANxRDHDtX/Fx9udgv0KrBBZSWwtEuQ4jzjYPacfu0V+l39vZQzO20YUiJRI2ypZpG2ORGLSybw9ToS0ZVebIOQdngnD3Ewhaxa5TaTl9Z+Yz8+ULGRJceR3MwwwcizA1QF/X7KJzTdd/Ys6ttxSpstJ8Npjsz3oYtIFmg5TTADOlgzEURaRxpAiBps92e8CRwoevGJuKZIXsCZYNoHX5ztqV67OCfABQccjjCyMfVtHoiFvmdMPaTHlb+YLMkRTJicWmFdrTBx0U3TksOq6HpZOBbNA8P3zQN9DUA3IBDJMZPDuMMuqjMtGlQyfMBcWQdbuwap2DshFrBYI3EQM0Ru9QBKyShkh0fiDtVcAIUYy8n7MdKy505HJNgpMY5+7NcoqhpVYzNgHTzV2BxJ7g+VK8f6GeYxQO6ybn5RCDKn85PKPWnEDzdYo6rtvNPVnFw3ycIg1n/E5kPGNtLSmCiBDqfRTNpZd5KMWPaea7pRrWijtxfeHjACarnKJu5GasjvHQOhNLPTlopig24Vu/jpZwHqdi3XLLR6u8zJoyHgi7tgRqi8Hra62yQw3WRRY2ATW0IBt5mMSHatv/TIicPCP6eaIawA4bjOSFaNDFTTLstYOEq+2pRLOG1MbfBlx3ukphd4TkqqXTXCbVWheYTie2oRQC/rCRFtIlkN2kjn57t7qrIicaqi0rYHeOVjfhfh4X8V+QCiBHNzEbc3UtqfwHrLrFLo5EWOVl7BATZ92kkD/NYh6xRsXOd3fgFAs/QMJy9SnJX0Z3pg4FuUQSeVG2NnDpqhMTvD8pMfSI+s1cPDx78ZVXL1Y45rmAp08mPE9LkcmRVFy0g1+Osc3vJPjiba9bEVjuIPkuCtluB+QfHV0aReuBS4hmR2oNRgOSuV9/G7eUSgd8Vng6qjsdrXgNX0vMk87/kpfqovRX1sDPHPZngPLLam3ks95ofRo9wXNCLRUTRYb+wuvOdpNAjudPrVxux6vsKlv+Gz0AOYceDMJiTuSJbsdKxHGn4GUWycMrHS9XF414nigz4lmAbZRHMsKjcocJWteGp4zbUpGqzRDVRrGuyX7Aw8Jn5fauGCmfZ2AHeLlXjO0HHV+nfLAsvnRakOmUio5ZQi5CX6PL01XO5ahRze63zXICflqDxafP0lFtTVhEfQQimo4LbBQcfEZK+wu8VaPAsipvrpwFchjC4FyS0ZQmGWrEZ2SrYd5L2pBD2XqKBzVAgqTPcZyboBogXe6qHumOp5LK9sBR2I5asoTYrWMusH1UcZEsAg46L6fjk7gL/eEvxHtUe9IzS5g2wQQ2CKk91FJxIAfkRhS6ExVyCGXHGg1ib6/QgKvWgS4PyrJ84Ye5wCc1NanAVk"
    }
  }
}
