apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share-frigate
  namespace: frigate
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 16Ti
  storageClassName: nfs-storage
  volumeMode: Filesystem
  volumeName: nfs-share-frigate
