---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: jenkins
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2dfecfb0000001e
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: jenkins
