apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  releaseName: jenkins
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
      version: "4.2.15"
  interval: 30m
  install:
    remediation:
      retries: 3
  dependsOn:
  - name: sealed-secrets-controller
    namespace: kube-system
  values:
  - name: jenkins-values
    kind: Secret
    optional: true
