---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre
spec:
  capacity:
    storage: 128Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: calibre
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2e0893a00000030
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: calibre
