apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "^23.3.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    prometheus:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: prometheus-cert
          hosts:
          - prometheus.web.bluehairfreak.com
        hosts:
        - prometheus.web.bluehairfreak.com
        path: /
      prometheusSpec:
        secrets: ['etcd-client-cert']
    kubeEtcd:
      serviceMonitor:
       scheme: https
       insecureSkipVerify: false
       serverName: localhost
       caFile: /etc/prometheus/secrets/etcd-client-cert/ca.crt
       certFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.crt
       keyFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.key
    grafana:
      sidecar:
        dashboards:
          searchNamespace: ALL
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: grafana
          hosts:
          - grafana.web.bluehairfreak.com
        hosts:
        - grafana.web.bluehairfreak.com
        path: /
    alertmanager:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: alertmanager-cert
          hosts:
          - alertmanager.web.bluehairfreak.com
        hosts:
        - alertmanager.web.bluehairfreak.com
        path: /
