apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  releaseName: overseerr
  chart:
    spec:
      chart: overseerr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "5.4.2"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.33.2
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: overseerr
          hosts:
          - requests.web.bluehairfreak.com
        hosts:
        - host: requests.web.bluehairfreak.com
          paths:
          - path: /
            pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: overseerr
      media:
        enabled: true
        existingClaim: nfs-share
