---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vxflexos
  csi:
    driver: csi-vxflexos.dellemc.com
    fsType: ext4
    volumeAttributes:
      FsType: ext4
      Name: stash
      StoragePoolID: "bf7590cf00000000"
      StoragePoolName: sp1
    volumeHandle: d2df785a00000003
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash
  namespace: stash
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: vxflexos
  volumeMode: Filesystem
  volumeName: stash
