apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mosquitto
resources:
  - ../../base/mosquitto
secretGenerator:
  - name: mosquitto-secret
    files:
      - values.yaml=values.yaml
