apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  releaseName: contour
  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "8.0.1"
  interval: 1h0m0s
  dependsOn:
  - name: metallb
    namespace: metallb-system
  install:
    remediation:
      retries: 3
  values:
    contour:
      image:
        tag: 1.21.1-debian-11-r0
    envoy:
      image:
        tag: 1.22.2-debian-11-r1
    commonLabels:
      prometheus: scrape
    metrics:
      serviceMonitor:
        namespace: "contour"
        enabled: false
        interval: "10s"
        scrapeTimeout: "1m"
