apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwarden
  namespace: shared-services
spec:
  releaseName: bitwarden
  chart:
    spec:
      chart: bitwarden
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: "2.1.11"
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          ingress.kubernetes.io/force-ssl-redirect: "true"
          kubernetes.io/ingress.class: contour
          kubernetes.io/tls-acme: "true"
        tls:
        - secretName: bitwarden
          hosts:
          - passwords.web.bluehairfreak.com
        hosts:
        - host: passwords.web.bluehairfreak.com
          paths:
          - path: /
            pathType: Prefix
    persistence:
      enabled: true
      existingClaim: bitwarden
    bitwardenrs:
      signupsAllowed: true
      admin:
        existingSecret:
          enabled: true
          name: "bitwarden-admin"
          tokenKey: "password"
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
