{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "vaultwarden-values",
    "namespace": "shared-services",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "vaultwarden-values",
        "namespace": "shared-services",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "values.yaml": "AgCPB/tgaaEWqZ/qpMr/N2E4y1/mxF73FuaPzgr6j04M82yhROYATZ8fVbR5CGIrttt9KGfE+tfnYt39wpzxQoX3cD/WkiFAHpYIzG1cv3/NCHhJ9b5tnC4piH9yKwLBe3QODx1j9n0VpNzqIXUDx9Qv1NEMdZN8o5G84Gj9QkW63D9xgvimAuM18Plzm0Ny+FoxdXQRNYU2s3b4Dzozm17vN2XD0SOul2DYdbvZB806409Qm/2YjTdFxQ16SPOD20nZaYF1aokcTv9LUv9EEEUZi/WPF4wGyOhl8jtanXvyBwRtAediXfVP4L8F7XyppK2eUxBRlsua1c9GL+65uRudkzQdBgG8j8NMx1FJJb1pEstgBLq+YRseMhU3dt6NWGxUkS82bm/J89reDwiL0zGiSE4c4vZBNOgYFLO/5iWtygCrMiKg3CRyzcSxTNRJTnDmJc5wS2kEQIqp6J39g3iWjFmvL9lkj//dn3v5sLY7j1w5LJhUo0W9RbVhbts77MWrR1hneKbjr8SKB8r2W4wi7hkoz5sa9I4C5u+O5UWFDJAgEOgEevKUaPZOM+PXh8LkvzeERBrdCnirBrmW1FT5/QmU/mb5f/kqAdgQWU2O+nQ33PZHOpBP8tE9KySeNBVb0r2CvN7lIy66OmgYlNsCaGRokHCrvcSuMnm9Q1BvTm1XJiH7Mk4247YsnWjpGsCKR4vy7dl1fgwy1bd9qqitLqKU0Xvn+k9dQbgGhkA/txau7ugIHGaJv71QLZtDZEkcQ5Y1lqme9nySrIGmDfkyE86ZC+k4YYnXLA4EzW3Mmu9+RqXHA3aC7zeqJRFou8BnJ1ZBkVmrMjcWRzDsQCsky10Jp1B8lb0t6HfGKdbClhTUdzfVFybpKF/FAM+DXN/wrA3d/UbYoEWAy/lI2kPcVABPJQ9ZomJvTEwRvlLE+/CGzmpr11Dpq/bop9XX4KogSN75ggOViJ9cCYl481z//5AHP/hcJZ88CyfZjOukZ8qiMk5pkFhvHaK+8b6bWGgkDvxHYmrbHBgsW2gIj667QPKpNUGHG09Sz6c5R0bn7DThR616nY+mDKtJuczZwllD8PZAyMK+pmSvyADZMmueDf1h23ywu7xJgMAwD6WcmuajoF6DWOmO5cnwikX/g/JlZ7IEMElp21D7uZgPmAXX17IoNMcFn8eyI7C84+/twChNT+CxWNImaEcCqOKo9Q712SNa9h5mOLTXs/N7CPZByUsRlfnAAfRYQxOVg8xi29LF3B8/8OBV46A2fIdqSAX2KG1amYopRm201a8rIKdiCmmanoWr240d7A=="
    }
  }
}
