---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: dev-cluster
spec:
  organization: example-org-8965f3
  secretsMountPath: "/tmp/secrets"
  module:
    source: "terraform-google-modules/kubernetes-engine/google"
    version: "16.1.0"
  runTriggers:
  - sourceableName: tf-operator-dev-vpc
  variables:
    - key: name
      value: dev-flux
      sensitive: false
      environmentVariable: false
    - key: region
      value: us-west1
      sensitive: false
      environmentVariable: false
    - key: ip_range_pods
      value: "us-west1-01-gke-01-pods"
      sensitive: false
      environmentVariable: false
    - key: ip_range_services
      value: "us-west1-01-gke-01-services"
      sensitive: false
      environmentVariable: false
    - key: network
      value: "dev-flux-vpc"
      sensitive: false
      environmentVariable: false
    - key: subnetwork
      value: "vpc-01"
      sensitive: false
      environmentVariable: false
    - key: node_pools
      value: |
        [
          {
            name = "default-node-pool"
            machine_type = "e2-medium"
            node_locations = "us-west1-b,us-west1-c"
            min_count = 1
            max_count = 4
            local_ssd_count = 0
            disk_size_gb = 100
            disk_type = "pd-standard"
            image_type = "COS"
            auto_repair = true
            auto_upgrade = true
            initial_node_count = 2
          },
        ]
      hcl: true
      sensitive: false
      environmentVariable: false
    - key: project_id
      sensitive: true
      environmentVariable: false
    - key: GOOGLE_CREDENTIALS
      sensitive: true
      environmentVariable: true
    - key: CONFIRM_DESTROY
      value: "1"
      sensitive: false
      environmentVariable: true

