---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: dev-vpc
spec:
  organization: example-org-8965f3
  secretsMountPath: "/tmp/secrets"
  module:
    source: "terraform-google-modules/network/google"
    version: "~> 3.0"
  runTrigger:
    sourceableName: tf-operator-tf-vpc
  variables:
    - key: network_name
      value: dev-flux-vpc
      sensitive: false
      environmentVariable: false
    - key: subnets
      value: |
        [
          {
            subnet_name = "vpc-01"
            subnet_ip = "10.10.10.0/24"
            subnet_region = "us-west1"
          }
        ]
      hcl: true
      sensitive: false
      environmentVariable: false
    - key: secondary_ranges
      value: |
        {
          vpc-01 = [
            {
              range_name = "us-west1-01-gke-01-pods"
              ip_cidr_range = "192.168.64.0/24"
            },
              range_name = "us-west1-01-gke-01-services"
              ip_cidr_range = "192.168.65.0/24"
            },
          ]
      }
      hcl: true
      sensitive: false
      environmentVariable: false
    - key: project_id
      sensitive: true
      environmentVariable: false
    - key: GOOGLE_CREDENTIALS
      sensitive: true
      environmentVariable: true
