apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-red
resources:
  - ../../base/node-red
secretGenerator:
  - name: node-red-secret
    files:
      - values.yaml=values.yaml
