apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  releaseName: istio-ingress
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.12.1"
  interval: 1h0m0s
  dependsOn:
  - name: metallb
    namespace: metallb-system
  install:
    remediation:
      retries: 3
  values:
    securityContext:
      allowPrivilegeEscalation: true
